name: forageralpha
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.5
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6
  modal_progress_hud: ^0.1.3
  flutter_webview_plugin: ^0.3.11
  http: ^0.12.1
  intl: ^0.16.1
  csv: ^4.0.3
  csv_reader: ^1.0.2
  firebase_admob: ^0.9.3+2
  url_launcher: ^5.4.11
  share: ^0.6.4+3
  mongo_dart:
    git:
      url: "https://github.com/tgercek/mongo_dart.git"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/images/forager_background.png
    - lib/images/forager1.png
    - lib/images/forager2.png
    - lib/images/forager3.png
    - lib/images/forager4.png
    - lib/images/forager5.png
    - lib/images/google_icon.png
    - lib/images/twitter_icon.png
    - lib/images/facebook_icon.png
    - lib/images/email_icon.png
    - lib/images/vegan_icon.png
    - lib/images/vegetarian_icon.png
    - lib/images/keto_icon.png
    - lib/images/paleo_icon.png
    - lib/images/salt_icon.png
    - lib/images/sugar_icon.png
    - lib/images/gluten_icon.png
    - lib/images/dairy_icon.png
    - lib/images/corn.png
    - lib/images/cookbook.png
    - lib/images/egg_icon.png
    - lib/images/fish_icon.png
    - lib/images/fodmap_icon.png
    - lib/images/balanced_icon.png
    - lib/images/highfiber_icon.png
    - lib/images/highprotein_icon.png
    - lib/images/lowcarb_icon.png
    - lib/images/lowfat_icon.png
    - lib/images/pescatarian_icon.png
    - lib/images/peanut_icon.png
    - lib/images/redmeat_icon.png
    - lib/images/sesame_icon.png
    - lib/images/soy_icon.png
    - lib/images/treenut_icon.png
    - lib/images/shellfish_icon.png
    - lib/images/heart_healthy.png
    - lib/images/pork_icon.png
    - lib/images/light.png
    - lib/images/sedentary.png
    - lib/images/moderate.png
    - lib/images/veryactive.png
    - lib/images/view_details.png
    - lib/images/instagram_social.png
    - lib/images/diabetic_friendly.png
    - lib/images/clean_eating.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GlacialBold
      fonts:
        - asset: lib/fonts/GlacialIndifference-Bold.ttf
    - family: GlacialRegular
      fonts:
        - asset: lib/fonts/GlacialIndifference-Regular.ttf
    - family: GlacialItalic
      fonts:
        - asset: lib/fonts/GlacialIndifference-Italic.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
